### PR TITLE
Add newrelic monitoring

### PR DESCRIPTION
**Pull request by go-dima**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by ghost** [comment]
Checking now.

**Review by vanessa-cooper — DISMISSED** [review]
Some issues need to be fixed before you can merge your PR:
 - Looks like you run npm install, but we're using yarn. Please remove "backend/package-lock.json" from your PR and use yarn instead.

**Review by ghost — CHANGES_REQUESTED** [review]
I see you've committed a license key to Git. Shouldn't do that, security-wise. Please remove the entire property from the config file, we'll add it as an environment variable.

**Review by ghost — APPROVED** [review]
Looking good! You can merge the PR now.

**Pull request merged**
